title: rainedoescode
author: Raine Adams
email:
description: > # this means to ignore newlines until "baseurl:"
  My personal blog, engineering journal, and exploration
  of the places where art and code meet

# social links
twitter_username: rainedoescode # DO NOT include the @ character, or else the build will fail!
github_username:  rainealexander # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
